import type { Metadata } from "next";
import { Head, Html, Main, NextScript } from "next/document";

export const metadata: Metadata = {
  title: "ZSTiO TV",
  description: "Generated by create next app",
};

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="UTF-8" />
      </Head>
      <body className="overflow-hidden bg-black text-[#f4f4f4]">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
